version: '3.5'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ROOT_USER: idios
      MINIO_ROOT_PASSWORD: AtadGhefDow2
    volumes:
      - minio:/data
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  milvus:
    build:
      context: .
      target: milvus
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus:/var/lib/milvus
    ports:
      - 19530:19530
      - 9091:9091
    depends_on:
      - etcd
      - minio
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  attu:
    image: zilliz/attu:latest
    ports:
      - 3000:3000
    environment:
      MILVUS_URL: milvus:19530

  api:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile
      target: api
    depends_on:
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_healthy
    environment:
      WEB_CONCURRENCY: 16
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    volumes:
      - ../api:/app
    ports:
      - 4213:4213
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 4213"
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  worker:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile
      target: worker
    depends_on:
      milvus:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      MILVUS_URL: milvus:19530
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      MILVUS_PASSWORD: password
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  dev:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile
      target: dev
    depends_on:
      milvus:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      MILVUS_URL: milvus:19530
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      MILVUS_PASSWORD: password
    volumes:
      - huggingface-cache:/home/user/.cache/huggingface
      - ../api:/app
    logging:
      options:
        max-size: "10M"
        max-file: "10"

volumes:
  etcd:
  minio:
  milvus:
  huggingface-cache:
  rabbitmq:
