version: '3.5'

services:
  api:
    image: idios-api:latest
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile
      target: api
    restart: unless-stopped
    ports:
      - 4213:4213
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      WEB_CONCURRENCY: 16
      RABBITMQ_URL: amqp://idios:dutEmoigAwd4@rabbitmq:5672 #TOEDIT
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 5672:5672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=idios
      - RABBITMQ_DEFAULT_PASS=dutEmoigAwd4 #TOEDIT
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    restart: unless-stopped
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: idios
      MINIO_ROOT_PASSWORD: AtadGhefDow2
    volumes:
      - ./volumes/minio:/data
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  milvus:
    image: milvusdb/milvus:v2.2.2
    restart: unless-stopped
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    command: milvus run standalone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/api/v1/health"]
      interval: 10s
      timeout: 1s
      retries: 5
    volumes:
      - ./milvus.yaml:/milvus/configs/milvus.yaml
      - ./volumes/milvus:/var/lib/milvus
    ports:
      - 19530:19530
    depends_on:
      - etcd
      - minio
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  worker:
    image: idios-worker:latest
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile
      target: worker
    restart: unless-stopped
    environment:
      MILVUS_URL: milvus:19530
      MILVUS_PASSWORD: FicopwadCer8 #TOEDIT
      RABBITMQ_URL: amqp://idios:dutEmoigAwd4@rabbitmq:5672 #TOEDIT
    logging:
      options:
        max-size: "10M"
        max-file: "10"
