version: '3.5'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    restart: unless-stopped
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: idios
      MINIO_ROOT_PASSWORD: AtadGhefDow2
    volumes:
      - minio:/data
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      options:
        max-size: "10M"
        max-file: "10"

  milvus:
    build:
      context: .
      target: milvus
    restart: unless-stopped
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus:/var/lib/milvus
    ports:
      - 19530:19530
    depends_on:
      - etcd
      - minio
    networks:
      default:
      reverse_proxy:
    labels:
      traefik.enable: 'true'
      traefik.http.routers.idios-milvus.entrypoints: websecure
      traefik.http.routers.idios-milvus.rule: Host(`milvus.idios.org`) #TOEDIT
      traefik.http.services.idios-milvus.loadbalancer.server.port: 9091
    logging:
      options:
        max-size: "10M"
        max-file: "10"

volumes:
  etcd:
  minio:
  milvus:

networks:
  reverse_proxy:
    external: true
